on:
  workflow_dispatch: 
    inputs:
      environment:
        description: "choose environement"
        required: true
        default: "stagging"
        type: choice
        options:
          - stagging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        run: echo "deploying the app..."
